### ISSUE TITLE
Getting genesis block throws NullPointerException

### ISSUE THREAD

**Issue by suadzh** [wavesplatform/WavesJ#47] opened 2019-08-21 15:05 UTC
Trying to get the genesis block will cause a NullPointerException because https://github.com/wavesplatform/WavesJ/blob/8685ba12728edeb8bdbc7f3ea77fcf140e2af9d5/src/main/java/com/wavesplatform/wavesj/json/deser/TransactionDeserializer.java#L29 will try to fetch the version even though genesis transactions don't have one.

**Steps to reproduce:**
```
Node node = new Node("https://nodes.wavesnodes.com", (byte) 'W');
node.getTransaction("2DVtfgXjpMeFf2PQCqvwxAiaGbiDsxDjSdNQkc5JQ74eWxjWFYgwvqzC4dn7iB1AhuM32WxEiVi1SGijsBtYQwn8");
```
**Result:**
```
Caused by: java.lang.NullPointerException
	at com.fasterxml.jackson.databind@2.9.8/com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2745)
	at wavesj@0.16/com.wavesplatform.wavesj.json.deser.TransactionDeserializer.deserialize(TransactionDeserializer.java:29)
	at wavesj@0.16/com.wavesplatform.wavesj.json.deser.TransactionDeserializer.deserialize(TransactionDeserializer.java:16)
	at com.fasterxml.jackson.databind@2.9.8/com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	... 21 more
```

**Comment by br0x** [comment] 2019-10-12 20:50
This is duplicate of issue #35

**Comment by msmolyakov** [comment] 2020-09-11 21:56
Please update to WavesJ 1.0.0. Now you can get both genesis block and genesis transactions:
```java
Node node = new Node(Profile.MAINNET);
Block genesisBlock = node.getGenesisBlock();

List<GenesisTransaction> txs = genesisBlock.transactions()
        .stream()
        .map(info -> (GenesisTransaction) info.tx())
        .collect(toList());

txs.forEach(tx -> System.out.println( tx.recipient() ));

System.out.println( node.getTransactionInfo(txs.get(0).id()) );
```

**Closed by msmolyakov** 2020-09-11 21:56 UTC
